// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wxipad.proto;

public interface BaseMsgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:BaseMsg)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>int32 ret = 1;</code>
     */
    int getRet();

    /**
     * <pre>
     * 请求接口
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    int getCmd();

    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    String getCmdUrl();

    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    com.google.protobuf.ByteString
    getCmdUrlBytes();

    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    String getShortHost();

    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    com.google.protobuf.ByteString
    getShortHostBytes();

    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    String getLongHost();

    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    com.google.protobuf.ByteString
    getLongHostBytes();

    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    boolean hasUser();

    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    User getUser();

    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    UserOrBuilder getUserOrBuilder();

    /**
     * <pre>
     * 长连接包头
     * </pre>
     *
     * <code>bytes longHead = 7;</code>
     */
    com.google.protobuf.ByteString getLongHead();

    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>bytes payloads = 8;</code>
     */
    com.google.protobuf.ByteString getPayloads();

    /**
     * <pre>
     * 扩展数据
     * </pre>
     *
     * <code>bytes playloadextend = 9;</code>
     */
    com.google.protobuf.ByteString getPlayloadextend();
}
