// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wxipad.proto;

/**
 * <pre>
 * 请求消息结构体
 * </pre>
 * <p>
 * Protobuf type {@code BaseMsg}
 */
public final class BaseMsg extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:BaseMsg)
        BaseMsgOrBuilder {
    public static final int RET_FIELD_NUMBER = 1;
    public static final int CMD_FIELD_NUMBER = 2;
    public static final int CMDURL_FIELD_NUMBER = 3;
    public static final int SHORTHOST_FIELD_NUMBER = 4;
    public static final int LONGHOST_FIELD_NUMBER = 5;
    public static final int USER_FIELD_NUMBER = 6;
    public static final int LONGHEAD_FIELD_NUMBER = 7;
    public static final int PAYLOADS_FIELD_NUMBER = 8;
    public static final int PLAYLOADEXTEND_FIELD_NUMBER = 9;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:BaseMsg)
    private static final BaseMsg DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<BaseMsg>
            PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
        public BaseMsg parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new BaseMsg(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new BaseMsg();
    }

    private int ret_;
    private int cmd_;
    private volatile Object cmdUrl_;
    private volatile Object shortHost_;
    private volatile Object longHost_;
    private User user_;
    private com.google.protobuf.ByteString longHead_;
    private com.google.protobuf.ByteString payloads_;
    private com.google.protobuf.ByteString playloadextend_;
    private byte memoizedIsInitialized = -1;

    // Use BaseMsg.newBuilder() to construct.
    private BaseMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private BaseMsg() {
        ret_ = 0;
        cmd_ = 0;
        cmdUrl_ = "";
        shortHost_ = "";
        longHost_ = "";
        longHead_ = com.google.protobuf.ByteString.EMPTY;
        payloads_ = com.google.protobuf.ByteString.EMPTY;
        playloadextend_ = com.google.protobuf.ByteString.EMPTY;
    }

    private BaseMsg(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        ret_ = input.readInt32();
                        break;
                    }
                    case 16: {

                        cmd_ = input.readInt32();
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        cmdUrl_ = s;
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        shortHost_ = s;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        longHost_ = s;
                        break;
                    }
                    case 50: {
                        User.Builder subBuilder = null;
                        if (user_ != null) {
                            subBuilder = user_.toBuilder();
                        }
                        user_ = input.readMessage(User.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(user_);
                            user_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 58: {

                        longHead_ = input.readBytes();
                        break;
                    }
                    case 66: {

                        payloads_ = input.readBytes();
                        break;
                    }
                    case 74: {

                        playloadextend_ = input.readBytes();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return WechatProto.internal_static_BaseMsg_descriptor;
    }

    public static BaseMsg parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static BaseMsg parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static BaseMsg parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static BaseMsg parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static BaseMsg parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static BaseMsg parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static BaseMsg parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static BaseMsg parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static BaseMsg parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static BaseMsg parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static BaseMsg parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static BaseMsg parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(BaseMsg prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static BaseMsg getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<BaseMsg> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return WechatProto.internal_static_BaseMsg_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        BaseMsg.class, Builder.class);
    }

    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>int32 ret = 1;</code>
     */
    @Override
    public int getRet() {
        return ret_;
    }

    /**
     * <pre>
     * 请求接口
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    @Override
    public int getCmd() {
        return cmd_;
    }

    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    @Override
    public String getCmdUrl() {
        Object ref = cmdUrl_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            cmdUrl_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getCmdUrlBytes() {
        Object ref = cmdUrl_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            cmdUrl_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    @Override
    public String getShortHost() {
        Object ref = shortHost_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            shortHost_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getShortHostBytes() {
        Object ref = shortHost_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            shortHost_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    public String getLongHost() {
        Object ref = longHost_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            longHost_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    public com.google.protobuf.ByteString
    getLongHostBytes() {
        Object ref = longHost_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            longHost_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    @Override
    public boolean hasUser() {
        return user_ != null;
    }

    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    @Override
    public User getUser() {
        return user_ == null ? User.getDefaultInstance() : user_;
    }

    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    @Override
    public UserOrBuilder getUserOrBuilder() {
        return getUser();
    }

    /**
     * <pre>
     * 长连接包头
     * </pre>
     *
     * <code>bytes longHead = 7;</code>
     */
    @Override
    public com.google.protobuf.ByteString getLongHead() {
        return longHead_;
    }

    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>bytes payloads = 8;</code>
     */
    @Override
    public com.google.protobuf.ByteString getPayloads() {
        return payloads_;
    }

    /**
     * <pre>
     * 扩展数据
     * </pre>
     *
     * <code>bytes playloadextend = 9;</code>
     */
    @Override
    public com.google.protobuf.ByteString getPlayloadextend() {
        return playloadextend_;
    }

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (ret_ != 0) {
            output.writeInt32(1, ret_);
        }
        if (cmd_ != 0) {
            output.writeInt32(2, cmd_);
        }
        if (!getCmdUrlBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cmdUrl_);
        }
        if (!getShortHostBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, shortHost_);
        }
        if (!getLongHostBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, longHost_);
        }
        if (user_ != null) {
            output.writeMessage(6, getUser());
        }
        if (!longHead_.isEmpty()) {
            output.writeBytes(7, longHead_);
        }
        if (!payloads_.isEmpty()) {
            output.writeBytes(8, payloads_);
        }
        if (!playloadextend_.isEmpty()) {
            output.writeBytes(9, playloadextend_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (ret_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, ret_);
        }
        if (cmd_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, cmd_);
        }
        if (!getCmdUrlBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cmdUrl_);
        }
        if (!getShortHostBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, shortHost_);
        }
        if (!getLongHostBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, longHost_);
        }
        if (user_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(6, getUser());
        }
        if (!longHead_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(7, longHead_);
        }
        if (!payloads_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(8, payloads_);
        }
        if (!playloadextend_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(9, playloadextend_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof BaseMsg)) {
            return super.equals(obj);
        }
        BaseMsg other = (BaseMsg) obj;

        boolean result = true;
        result = result && (getRet()
                == other.getRet());
        result = result && (getCmd()
                == other.getCmd());
        result = result && getCmdUrl()
                .equals(other.getCmdUrl());
        result = result && getShortHost()
                .equals(other.getShortHost());
        result = result && getLongHost()
                .equals(other.getLongHost());
        result = result && (hasUser() == other.hasUser());
        if (hasUser()) {
            result = result && getUser()
                    .equals(other.getUser());
        }
        result = result && getLongHead()
                .equals(other.getLongHead());
        result = result && getPayloads()
                .equals(other.getPayloads());
        result = result && getPlayloadextend()
                .equals(other.getPlayloadextend());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + RET_FIELD_NUMBER;
        hash = (53 * hash) + getRet();
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + getCmd();
        hash = (37 * hash) + CMDURL_FIELD_NUMBER;
        hash = (53 * hash) + getCmdUrl().hashCode();
        hash = (37 * hash) + SHORTHOST_FIELD_NUMBER;
        hash = (53 * hash) + getShortHost().hashCode();
        hash = (37 * hash) + LONGHOST_FIELD_NUMBER;
        hash = (53 * hash) + getLongHost().hashCode();
        if (hasUser()) {
            hash = (37 * hash) + USER_FIELD_NUMBER;
            hash = (53 * hash) + getUser().hashCode();
        }
        hash = (37 * hash) + LONGHEAD_FIELD_NUMBER;
        hash = (53 * hash) + getLongHead().hashCode();
        hash = (37 * hash) + PAYLOADS_FIELD_NUMBER;
        hash = (53 * hash) + getPayloads().hashCode();
        hash = (37 * hash) + PLAYLOADEXTEND_FIELD_NUMBER;
        hash = (53 * hash) + getPlayloadextend().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<BaseMsg> getParserForType() {
        return PARSER;
    }

    @Override
    public BaseMsg getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     * <p>
     * Protobuf type {@code BaseMsg}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:BaseMsg)
            BaseMsgOrBuilder {
        private int ret_;
        private int cmd_;
        private Object cmdUrl_ = "";
        private Object shortHost_ = "";
        private Object longHost_ = "";
        private User user_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                User, User.Builder, UserOrBuilder> userBuilder_;
        private com.google.protobuf.ByteString longHead_ = com.google.protobuf.ByteString.EMPTY;
        private com.google.protobuf.ByteString payloads_ = com.google.protobuf.ByteString.EMPTY;
        private com.google.protobuf.ByteString playloadextend_ = com.google.protobuf.ByteString.EMPTY;

        // Construct using BaseMsg.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return WechatProto.internal_static_BaseMsg_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return WechatProto.internal_static_BaseMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            BaseMsg.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            ret_ = 0;

            cmd_ = 0;

            cmdUrl_ = "";

            shortHost_ = "";

            longHost_ = "";

            if (userBuilder_ == null) {
                user_ = null;
            } else {
                user_ = null;
                userBuilder_ = null;
            }
            longHead_ = com.google.protobuf.ByteString.EMPTY;

            payloads_ = com.google.protobuf.ByteString.EMPTY;

            playloadextend_ = com.google.protobuf.ByteString.EMPTY;

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return WechatProto.internal_static_BaseMsg_descriptor;
        }

        @Override
        public BaseMsg getDefaultInstanceForType() {
            return BaseMsg.getDefaultInstance();
        }

        @Override
        public BaseMsg build() {
            BaseMsg result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public BaseMsg buildPartial() {
            BaseMsg result = new BaseMsg(this);
            result.ret_ = ret_;
            result.cmd_ = cmd_;
            result.cmdUrl_ = cmdUrl_;
            result.shortHost_ = shortHost_;
            result.longHost_ = longHost_;
            if (userBuilder_ == null) {
                result.user_ = user_;
            } else {
                result.user_ = userBuilder_.build();
            }
            result.longHead_ = longHead_;
            result.payloads_ = payloads_;
            result.playloadextend_ = playloadextend_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return (Builder) super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof BaseMsg) {
                return mergeFrom((BaseMsg) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(BaseMsg other) {
            if (other == BaseMsg.getDefaultInstance()) {
                return this;
            }
            if (other.getRet() != 0) {
                setRet(other.getRet());
            }
            if (other.getCmd() != 0) {
                setCmd(other.getCmd());
            }
            if (!other.getCmdUrl().isEmpty()) {
                cmdUrl_ = other.cmdUrl_;
                onChanged();
            }
            if (!other.getShortHost().isEmpty()) {
                shortHost_ = other.shortHost_;
                onChanged();
            }
            if (!other.getLongHost().isEmpty()) {
                longHost_ = other.longHost_;
                onChanged();
            }
            if (other.hasUser()) {
                mergeUser(other.getUser());
            }
            if (other.getLongHead() != com.google.protobuf.ByteString.EMPTY) {
                setLongHead(other.getLongHead());
            }
            if (other.getPayloads() != com.google.protobuf.ByteString.EMPTY) {
                setPayloads(other.getPayloads());
            }
            if (other.getPlayloadextend() != com.google.protobuf.ByteString.EMPTY) {
                setPlayloadextend(other.getPlayloadextend());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            BaseMsg parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (BaseMsg) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <pre>
         * 状态码
         * </pre>
         *
         * <code>int32 ret = 1;</code>
         */
        @Override
        public int getRet() {
            return ret_;
        }

        /**
         * <pre>
         * 状态码
         * </pre>
         *
         * <code>int32 ret = 1;</code>
         */
        public Builder setRet(int value) {

            ret_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 状态码
         * </pre>
         *
         * <code>int32 ret = 1;</code>
         */
        public Builder clearRet() {

            ret_ = 0;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 请求接口
         * </pre>
         *
         * <code>int32 cmd = 2;</code>
         */
        @Override
        public int getCmd() {
            return cmd_;
        }

        /**
         * <pre>
         * 请求接口
         * </pre>
         *
         * <code>int32 cmd = 2;</code>
         */
        public Builder setCmd(int value) {

            cmd_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 请求接口
         * </pre>
         *
         * <code>int32 cmd = 2;</code>
         */
        public Builder clearCmd() {

            cmd_ = 0;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 接口连接
         * </pre>
         *
         * <code>string cmdUrl = 3;</code>
         */
        @Override
        public String getCmdUrl() {
            Object ref = cmdUrl_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                cmdUrl_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 接口连接
         * </pre>
         *
         * <code>string cmdUrl = 3;</code>
         */
        public Builder setCmdUrl(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            cmdUrl_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 接口连接
         * </pre>
         *
         * <code>string cmdUrl = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getCmdUrlBytes() {
            Object ref = cmdUrl_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                cmdUrl_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 接口连接
         * </pre>
         *
         * <code>string cmdUrl = 3;</code>
         */
        public Builder setCmdUrlBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            cmdUrl_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 接口连接
         * </pre>
         *
         * <code>string cmdUrl = 3;</code>
         */
        public Builder clearCmdUrl() {

            cmdUrl_ = getDefaultInstance().getCmdUrl();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 短连接地址
         * </pre>
         *
         * <code>string shortHost = 4;</code>
         */
        @Override
        public String getShortHost() {
            Object ref = shortHost_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                shortHost_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 短连接地址
         * </pre>
         *
         * <code>string shortHost = 4;</code>
         */
        public Builder setShortHost(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            shortHost_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 短连接地址
         * </pre>
         *
         * <code>string shortHost = 4;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getShortHostBytes() {
            Object ref = shortHost_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                shortHost_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 短连接地址
         * </pre>
         *
         * <code>string shortHost = 4;</code>
         */
        public Builder setShortHostBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            shortHost_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 短连接地址
         * </pre>
         *
         * <code>string shortHost = 4;</code>
         */
        public Builder clearShortHost() {

            shortHost_ = getDefaultInstance().getShortHost();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 长链接地址
         * </pre>
         *
         * <code>string longHost = 5;</code>
         */
        public String getLongHost() {
            Object ref = longHost_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                longHost_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 长链接地址
         * </pre>
         *
         * <code>string longHost = 5;</code>
         */
        public Builder setLongHost(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            longHost_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 长链接地址
         * </pre>
         *
         * <code>string longHost = 5;</code>
         */
        public com.google.protobuf.ByteString
        getLongHostBytes() {
            Object ref = longHost_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                longHost_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 长链接地址
         * </pre>
         *
         * <code>string longHost = 5;</code>
         */
        public Builder setLongHostBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            longHost_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 长链接地址
         * </pre>
         *
         * <code>string longHost = 5;</code>
         */
        public Builder clearLongHost() {

            longHost_ = getDefaultInstance().getLongHost();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        @Override
        public boolean hasUser() {
            return userBuilder_ != null || user_ != null;
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        @Override
        public User getUser() {
            if (userBuilder_ == null) {
                return user_ == null ? User.getDefaultInstance() : user_;
            } else {
                return userBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        public Builder setUser(User value) {
            if (userBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                user_ = value;
                onChanged();
            } else {
                userBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        public Builder setUser(
                User.Builder builderForValue) {
            if (userBuilder_ == null) {
                user_ = builderForValue.build();
                onChanged();
            } else {
                userBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        public Builder mergeUser(User value) {
            if (userBuilder_ == null) {
                if (user_ != null) {
                    user_ =
                            User.newBuilder(user_).mergeFrom(value).buildPartial();
                } else {
                    user_ = value;
                }
                onChanged();
            } else {
                userBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        public Builder clearUser() {
            if (userBuilder_ == null) {
                user_ = null;
                onChanged();
            } else {
                user_ = null;
                userBuilder_ = null;
            }

            return this;
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        public User.Builder getUserBuilder() {

            onChanged();
            return getUserFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        @Override
        public UserOrBuilder getUserOrBuilder() {
            if (userBuilder_ != null) {
                return userBuilder_.getMessageOrBuilder();
            } else {
                return user_ == null ?
                        User.getDefaultInstance() : user_;
            }
        }

        /**
         * <pre>
         * 当前微信号结构体
         * </pre>
         *
         * <code>.User user = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                User, User.Builder, UserOrBuilder>
        getUserFieldBuilder() {
            if (userBuilder_ == null) {
                userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        User, User.Builder, UserOrBuilder>(
                        getUser(),
                        getParentForChildren(),
                        isClean());
                user_ = null;
            }
            return userBuilder_;
        }

        /**
         * <pre>
         * 长连接包头
         * </pre>
         *
         * <code>bytes longHead = 7;</code>
         */
        @Override
        public com.google.protobuf.ByteString getLongHead() {
            return longHead_;
        }

        /**
         * <pre>
         * 长连接包头
         * </pre>
         *
         * <code>bytes longHead = 7;</code>
         */
        public Builder setLongHead(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            longHead_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 长连接包头
         * </pre>
         *
         * <code>bytes longHead = 7;</code>
         */
        public Builder clearLongHead() {

            longHead_ = getDefaultInstance().getLongHead();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 数据
         * </pre>
         *
         * <code>bytes payloads = 8;</code>
         */
        @Override
        public com.google.protobuf.ByteString getPayloads() {
            return payloads_;
        }

        /**
         * <pre>
         * 数据
         * </pre>
         *
         * <code>bytes payloads = 8;</code>
         */
        public Builder setPayloads(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            payloads_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 数据
         * </pre>
         *
         * <code>bytes payloads = 8;</code>
         */
        public Builder clearPayloads() {

            payloads_ = getDefaultInstance().getPayloads();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 扩展数据
         * </pre>
         *
         * <code>bytes playloadextend = 9;</code>
         */
        @Override
        public com.google.protobuf.ByteString getPlayloadextend() {
            return playloadextend_;
        }

        /**
         * <pre>
         * 扩展数据
         * </pre>
         *
         * <code>bytes playloadextend = 9;</code>
         */
        public Builder setPlayloadextend(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            playloadextend_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 扩展数据
         * </pre>
         *
         * <code>bytes playloadextend = 9;</code>
         */
        public Builder clearPlayloadextend() {

            playloadextend_ = getDefaultInstance().getPlayloadextend();
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:BaseMsg)
    }

}

