// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wxipad.proto;

/**
 * <pre>
 * 当前微信号结构体
 * </pre>
 * <p>
 * Protobuf type {@code User}
 */
public final class User extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:User)
        UserOrBuilder {
    public static final int UIN_FIELD_NUMBER = 1;
    public static final int COOKIES_FIELD_NUMBER = 2;
    public static final int SESSIONKEY_FIELD_NUMBER = 3;
    public static final int DEVICEID_FIELD_NUMBER = 4;
    public static final int DEVICETYPE_FIELD_NUMBER = 5;
    public static final int DEVICENAME_FIELD_NUMBER = 6;
    public static final int CURRENTSYNCKEY_FIELD_NUMBER = 7;
    public static final int MAXSYNCKEY_FIELD_NUMBER = 8;
    public static final int AUTOAUTHKEY_FIELD_NUMBER = 9;
    public static final int USERAME_FIELD_NUMBER = 10;
    public static final int NICKNAME_FIELD_NUMBER = 11;
    public static final int USEREXT_FIELD_NUMBER = 12;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:User)
    private static final User DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<User>
            PARSER = new com.google.protobuf.AbstractParser<User>() {
        public User parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new User(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new User();
    }

    private long uin_;
    private com.google.protobuf.ByteString cookies_;
    private com.google.protobuf.ByteString sessionKey_;
    private volatile Object deviceId_;
    private volatile Object deviceType_;
    private volatile Object deviceName_;
    private com.google.protobuf.ByteString currentsyncKey_;
    private com.google.protobuf.ByteString maxSyncKey_;
    private com.google.protobuf.ByteString autoAuthKey_;
    private volatile Object userame_;
    private com.google.protobuf.ByteString nickname_;
    private com.google.protobuf.ByteString userExt_;
    private byte memoizedIsInitialized = -1;

    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private User() {
        uin_ = 0L;
        cookies_ = com.google.protobuf.ByteString.EMPTY;
        sessionKey_ = com.google.protobuf.ByteString.EMPTY;
        deviceId_ = "";
        deviceType_ = "";
        deviceName_ = "";
        currentsyncKey_ = com.google.protobuf.ByteString.EMPTY;
        maxSyncKey_ = com.google.protobuf.ByteString.EMPTY;
        autoAuthKey_ = com.google.protobuf.ByteString.EMPTY;
        userame_ = "";
        nickname_ = com.google.protobuf.ByteString.EMPTY;
        userExt_ = com.google.protobuf.ByteString.EMPTY;
    }

    private User(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        uin_ = input.readInt64();
                        break;
                    }
                    case 18: {

                        cookies_ = input.readBytes();
                        break;
                    }
                    case 26: {

                        sessionKey_ = input.readBytes();
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        deviceId_ = s;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        deviceType_ = s;
                        break;
                    }
                    case 50: {
                        String s = input.readStringRequireUtf8();

                        deviceName_ = s;
                        break;
                    }
                    case 58: {

                        currentsyncKey_ = input.readBytes();
                        break;
                    }
                    case 66: {

                        maxSyncKey_ = input.readBytes();
                        break;
                    }
                    case 74: {

                        autoAuthKey_ = input.readBytes();
                        break;
                    }
                    case 82: {
                        String s = input.readStringRequireUtf8();

                        userame_ = s;
                        break;
                    }
                    case 90: {

                        nickname_ = input.readBytes();
                        break;
                    }
                    case 98: {

                        userExt_ = input.readBytes();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return WechatProto.internal_static_User_descriptor;
    }

    public static User parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static User parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static User parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static User parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static User parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static User parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static User parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static User parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static User parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static User parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static User parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static User parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(User prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static User getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<User> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return WechatProto.internal_static_User_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        User.class, Builder.class);
    }

    /**
     * <pre>
     * 标识
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    @Override
    public long getUin() {
        return uin_;
    }

    /**
     * <pre>
     * 网络跟踪key
     * </pre>
     *
     * <code>bytes cookies = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getCookies() {
        return cookies_;
    }

    /**
     * <pre>
     * 会话密钥
     * </pre>
     *
     * <code>bytes sessionKey = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString getSessionKey() {
        return sessionKey_;
    }

    /**
     * <pre>
     * 设备 ID
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     */
    @Override
    public String getDeviceId() {
        Object ref = deviceId_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            deviceId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 设备 ID
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            deviceId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>string deviceType = 5;</code>
     */
    @Override
    public String getDeviceType() {
        Object ref = deviceType_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            deviceType_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>string deviceType = 5;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getDeviceTypeBytes() {
        Object ref = deviceType_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            deviceType_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 设备名字
     * </pre>
     *
     * <code>string deviceName = 6;</code>
     */
    @Override
    public String getDeviceName() {
        Object ref = deviceName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            deviceName_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 设备名字
     * </pre>
     *
     * <code>string deviceName = 6;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getDeviceNameBytes() {
        Object ref = deviceName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            deviceName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 当前同步 KEY
     * </pre>
     *
     * <code>bytes currentsyncKey = 7;</code>
     */
    @Override
    public com.google.protobuf.ByteString getCurrentsyncKey() {
        return currentsyncKey_;
    }

    /**
     * <pre>
     * 同步消息 KEY
     * </pre>
     *
     * <code>bytes maxSyncKey = 8;</code>
     */
    @Override
    public com.google.protobuf.ByteString getMaxSyncKey() {
        return maxSyncKey_;
    }

    /**
     * <pre>
     * 自动授权 KEY
     * </pre>
     *
     * <code>bytes autoAuthKey = 9;</code>
     */
    @Override
    public com.google.protobuf.ByteString getAutoAuthKey() {
        return autoAuthKey_;
    }

    /**
     * <pre>
     * 微信 ID
     * </pre>
     *
     * <code>string userame = 10;</code>
     */
    @Override
    public String getUserame() {
        Object ref = userame_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            userame_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 微信 ID
     * </pre>
     *
     * <code>string userame = 10;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getUserameBytes() {
        Object ref = userame_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            userame_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 微信昵称
     * </pre>
     *
     * <code>bytes nickname = 11;</code>
     */
    @Override
    public com.google.protobuf.ByteString getNickname() {
        return nickname_;
    }

    /**
     * <pre>
     * 用户插件
     * </pre>
     *
     * <code>bytes userExt = 12;</code>
     */
    @Override
    public com.google.protobuf.ByteString getUserExt() {
        return userExt_;
    }

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (uin_ != 0L) {
            output.writeInt64(1, uin_);
        }
        if (!cookies_.isEmpty()) {
            output.writeBytes(2, cookies_);
        }
        if (!sessionKey_.isEmpty()) {
            output.writeBytes(3, sessionKey_);
        }
        if (!getDeviceIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceId_);
        }
        if (!getDeviceTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceType_);
        }
        if (!getDeviceNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, deviceName_);
        }
        if (!currentsyncKey_.isEmpty()) {
            output.writeBytes(7, currentsyncKey_);
        }
        if (!maxSyncKey_.isEmpty()) {
            output.writeBytes(8, maxSyncKey_);
        }
        if (!autoAuthKey_.isEmpty()) {
            output.writeBytes(9, autoAuthKey_);
        }
        if (!getUserameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 10, userame_);
        }
        if (!nickname_.isEmpty()) {
            output.writeBytes(11, nickname_);
        }
        if (!userExt_.isEmpty()) {
            output.writeBytes(12, userExt_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (uin_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, uin_);
        }
        if (!cookies_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(2, cookies_);
        }
        if (!sessionKey_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(3, sessionKey_);
        }
        if (!getDeviceIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceId_);
        }
        if (!getDeviceTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceType_);
        }
        if (!getDeviceNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, deviceName_);
        }
        if (!currentsyncKey_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(7, currentsyncKey_);
        }
        if (!maxSyncKey_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(8, maxSyncKey_);
        }
        if (!autoAuthKey_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(9, autoAuthKey_);
        }
        if (!getUserameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, userame_);
        }
        if (!nickname_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(11, nickname_);
        }
        if (!userExt_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(12, userExt_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof User)) {
            return super.equals(obj);
        }
        User other = (User) obj;

        boolean result = true;
        result = result && (getUin()
                == other.getUin());
        result = result && getCookies()
                .equals(other.getCookies());
        result = result && getSessionKey()
                .equals(other.getSessionKey());
        result = result && getDeviceId()
                .equals(other.getDeviceId());
        result = result && getDeviceType()
                .equals(other.getDeviceType());
        result = result && getDeviceName()
                .equals(other.getDeviceName());
        result = result && getCurrentsyncKey()
                .equals(other.getCurrentsyncKey());
        result = result && getMaxSyncKey()
                .equals(other.getMaxSyncKey());
        result = result && getAutoAuthKey()
                .equals(other.getAutoAuthKey());
        result = result && getUserame()
                .equals(other.getUserame());
        result = result && getNickname()
                .equals(other.getNickname());
        result = result && getUserExt()
                .equals(other.getUserExt());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + UIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getUin());
        hash = (37 * hash) + COOKIES_FIELD_NUMBER;
        hash = (53 * hash) + getCookies().hashCode();
        hash = (37 * hash) + SESSIONKEY_FIELD_NUMBER;
        hash = (53 * hash) + getSessionKey().hashCode();
        hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceId().hashCode();
        hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceType().hashCode();
        hash = (37 * hash) + DEVICENAME_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceName().hashCode();
        hash = (37 * hash) + CURRENTSYNCKEY_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentsyncKey().hashCode();
        hash = (37 * hash) + MAXSYNCKEY_FIELD_NUMBER;
        hash = (53 * hash) + getMaxSyncKey().hashCode();
        hash = (37 * hash) + AUTOAUTHKEY_FIELD_NUMBER;
        hash = (53 * hash) + getAutoAuthKey().hashCode();
        hash = (37 * hash) + USERAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserame().hashCode();
        hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
        hash = (53 * hash) + getNickname().hashCode();
        hash = (37 * hash) + USEREXT_FIELD_NUMBER;
        hash = (53 * hash) + getUserExt().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<User> getParserForType() {
        return PARSER;
    }

    @Override
    public User getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     * <p>
     * Protobuf type {@code User}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:User)
            UserOrBuilder {
        private long uin_;
        private com.google.protobuf.ByteString cookies_ = com.google.protobuf.ByteString.EMPTY;
        private com.google.protobuf.ByteString sessionKey_ = com.google.protobuf.ByteString.EMPTY;
        private Object deviceId_ = "";
        private Object deviceType_ = "";
        private Object deviceName_ = "";
        private com.google.protobuf.ByteString currentsyncKey_ = com.google.protobuf.ByteString.EMPTY;
        private com.google.protobuf.ByteString maxSyncKey_ = com.google.protobuf.ByteString.EMPTY;
        private com.google.protobuf.ByteString autoAuthKey_ = com.google.protobuf.ByteString.EMPTY;
        private Object userame_ = "";
        private com.google.protobuf.ByteString nickname_ = com.google.protobuf.ByteString.EMPTY;
        private com.google.protobuf.ByteString userExt_ = com.google.protobuf.ByteString.EMPTY;

        // Construct using User.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return WechatProto.internal_static_User_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return WechatProto.internal_static_User_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            User.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            uin_ = 0L;

            cookies_ = com.google.protobuf.ByteString.EMPTY;

            sessionKey_ = com.google.protobuf.ByteString.EMPTY;

            deviceId_ = "";

            deviceType_ = "";

            deviceName_ = "";

            currentsyncKey_ = com.google.protobuf.ByteString.EMPTY;

            maxSyncKey_ = com.google.protobuf.ByteString.EMPTY;

            autoAuthKey_ = com.google.protobuf.ByteString.EMPTY;

            userame_ = "";

            nickname_ = com.google.protobuf.ByteString.EMPTY;

            userExt_ = com.google.protobuf.ByteString.EMPTY;

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return WechatProto.internal_static_User_descriptor;
        }

        @Override
        public User getDefaultInstanceForType() {
            return User.getDefaultInstance();
        }

        @Override
        public User build() {
            User result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public User buildPartial() {
            User result = new User(this);
            result.uin_ = uin_;
            result.cookies_ = cookies_;
            result.sessionKey_ = sessionKey_;
            result.deviceId_ = deviceId_;
            result.deviceType_ = deviceType_;
            result.deviceName_ = deviceName_;
            result.currentsyncKey_ = currentsyncKey_;
            result.maxSyncKey_ = maxSyncKey_;
            result.autoAuthKey_ = autoAuthKey_;
            result.userame_ = userame_;
            result.nickname_ = nickname_;
            result.userExt_ = userExt_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return (Builder) super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof User) {
                return mergeFrom((User) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(User other) {
            if (other == User.getDefaultInstance()) {
                return this;
            }
            if (other.getUin() != 0L) {
                setUin(other.getUin());
            }
            if (other.getCookies() != com.google.protobuf.ByteString.EMPTY) {
                setCookies(other.getCookies());
            }
            if (other.getSessionKey() != com.google.protobuf.ByteString.EMPTY) {
                setSessionKey(other.getSessionKey());
            }
            if (!other.getDeviceId().isEmpty()) {
                deviceId_ = other.deviceId_;
                onChanged();
            }
            if (!other.getDeviceType().isEmpty()) {
                deviceType_ = other.deviceType_;
                onChanged();
            }
            if (!other.getDeviceName().isEmpty()) {
                deviceName_ = other.deviceName_;
                onChanged();
            }
            if (other.getCurrentsyncKey() != com.google.protobuf.ByteString.EMPTY) {
                setCurrentsyncKey(other.getCurrentsyncKey());
            }
            if (other.getMaxSyncKey() != com.google.protobuf.ByteString.EMPTY) {
                setMaxSyncKey(other.getMaxSyncKey());
            }
            if (other.getAutoAuthKey() != com.google.protobuf.ByteString.EMPTY) {
                setAutoAuthKey(other.getAutoAuthKey());
            }
            if (!other.getUserame().isEmpty()) {
                userame_ = other.userame_;
                onChanged();
            }
            if (other.getNickname() != com.google.protobuf.ByteString.EMPTY) {
                setNickname(other.getNickname());
            }
            if (other.getUserExt() != com.google.protobuf.ByteString.EMPTY) {
                setUserExt(other.getUserExt());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            User parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (User) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <pre>
         * 标识
         * </pre>
         *
         * <code>int64 uin = 1;</code>
         */
        @Override
        public long getUin() {
            return uin_;
        }

        /**
         * <pre>
         * 标识
         * </pre>
         *
         * <code>int64 uin = 1;</code>
         */
        public Builder setUin(long value) {

            uin_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 标识
         * </pre>
         *
         * <code>int64 uin = 1;</code>
         */
        public Builder clearUin() {

            uin_ = 0L;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 网络跟踪key
         * </pre>
         *
         * <code>bytes cookies = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString getCookies() {
            return cookies_;
        }

        /**
         * <pre>
         * 网络跟踪key
         * </pre>
         *
         * <code>bytes cookies = 2;</code>
         */
        public Builder setCookies(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            cookies_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 网络跟踪key
         * </pre>
         *
         * <code>bytes cookies = 2;</code>
         */
        public Builder clearCookies() {

            cookies_ = getDefaultInstance().getCookies();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 会话密钥
         * </pre>
         *
         * <code>bytes sessionKey = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString getSessionKey() {
            return sessionKey_;
        }

        /**
         * <pre>
         * 会话密钥
         * </pre>
         *
         * <code>bytes sessionKey = 3;</code>
         */
        public Builder setSessionKey(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            sessionKey_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 会话密钥
         * </pre>
         *
         * <code>bytes sessionKey = 3;</code>
         */
        public Builder clearSessionKey() {

            sessionKey_ = getDefaultInstance().getSessionKey();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备 ID
         * </pre>
         *
         * <code>string deviceId = 4;</code>
         */
        @Override
        public String getDeviceId() {
            Object ref = deviceId_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                deviceId_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 设备 ID
         * </pre>
         *
         * <code>string deviceId = 4;</code>
         */
        public Builder setDeviceId(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            deviceId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备 ID
         * </pre>
         *
         * <code>string deviceId = 4;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getDeviceIdBytes() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                deviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 设备 ID
         * </pre>
         *
         * <code>string deviceId = 4;</code>
         */
        public Builder setDeviceIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            deviceId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备 ID
         * </pre>
         *
         * <code>string deviceId = 4;</code>
         */
        public Builder clearDeviceId() {

            deviceId_ = getDefaultInstance().getDeviceId();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备类型
         * </pre>
         *
         * <code>string deviceType = 5;</code>
         */
        @Override
        public String getDeviceType() {
            Object ref = deviceType_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                deviceType_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 设备类型
         * </pre>
         *
         * <code>string deviceType = 5;</code>
         */
        public Builder setDeviceType(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            deviceType_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备类型
         * </pre>
         *
         * <code>string deviceType = 5;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
            Object ref = deviceType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                deviceType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 设备类型
         * </pre>
         *
         * <code>string deviceType = 5;</code>
         */
        public Builder setDeviceTypeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            deviceType_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备类型
         * </pre>
         *
         * <code>string deviceType = 5;</code>
         */
        public Builder clearDeviceType() {

            deviceType_ = getDefaultInstance().getDeviceType();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备名字
         * </pre>
         *
         * <code>string deviceName = 6;</code>
         */
        @Override
        public String getDeviceName() {
            Object ref = deviceName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                deviceName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 设备名字
         * </pre>
         *
         * <code>string deviceName = 6;</code>
         */
        public Builder setDeviceName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            deviceName_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备名字
         * </pre>
         *
         * <code>string deviceName = 6;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getDeviceNameBytes() {
            Object ref = deviceName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                deviceName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 设备名字
         * </pre>
         *
         * <code>string deviceName = 6;</code>
         */
        public Builder setDeviceNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            deviceName_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 设备名字
         * </pre>
         *
         * <code>string deviceName = 6;</code>
         */
        public Builder clearDeviceName() {

            deviceName_ = getDefaultInstance().getDeviceName();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 当前同步 KEY
         * </pre>
         *
         * <code>bytes currentsyncKey = 7;</code>
         */
        @Override
        public com.google.protobuf.ByteString getCurrentsyncKey() {
            return currentsyncKey_;
        }

        /**
         * <pre>
         * 当前同步 KEY
         * </pre>
         *
         * <code>bytes currentsyncKey = 7;</code>
         */
        public Builder setCurrentsyncKey(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            currentsyncKey_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 当前同步 KEY
         * </pre>
         *
         * <code>bytes currentsyncKey = 7;</code>
         */
        public Builder clearCurrentsyncKey() {

            currentsyncKey_ = getDefaultInstance().getCurrentsyncKey();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 同步消息 KEY
         * </pre>
         *
         * <code>bytes maxSyncKey = 8;</code>
         */
        @Override
        public com.google.protobuf.ByteString getMaxSyncKey() {
            return maxSyncKey_;
        }

        /**
         * <pre>
         * 同步消息 KEY
         * </pre>
         *
         * <code>bytes maxSyncKey = 8;</code>
         */
        public Builder setMaxSyncKey(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            maxSyncKey_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 同步消息 KEY
         * </pre>
         *
         * <code>bytes maxSyncKey = 8;</code>
         */
        public Builder clearMaxSyncKey() {

            maxSyncKey_ = getDefaultInstance().getMaxSyncKey();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 自动授权 KEY
         * </pre>
         *
         * <code>bytes autoAuthKey = 9;</code>
         */
        @Override
        public com.google.protobuf.ByteString getAutoAuthKey() {
            return autoAuthKey_;
        }

        /**
         * <pre>
         * 自动授权 KEY
         * </pre>
         *
         * <code>bytes autoAuthKey = 9;</code>
         */
        public Builder setAutoAuthKey(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            autoAuthKey_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 自动授权 KEY
         * </pre>
         *
         * <code>bytes autoAuthKey = 9;</code>
         */
        public Builder clearAutoAuthKey() {

            autoAuthKey_ = getDefaultInstance().getAutoAuthKey();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 微信 ID
         * </pre>
         *
         * <code>string userame = 10;</code>
         */
        @Override
        public String getUserame() {
            Object ref = userame_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                userame_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 微信 ID
         * </pre>
         *
         * <code>string userame = 10;</code>
         */
        public Builder setUserame(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            userame_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 微信 ID
         * </pre>
         *
         * <code>string userame = 10;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getUserameBytes() {
            Object ref = userame_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userame_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 微信 ID
         * </pre>
         *
         * <code>string userame = 10;</code>
         */
        public Builder setUserameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            userame_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 微信 ID
         * </pre>
         *
         * <code>string userame = 10;</code>
         */
        public Builder clearUserame() {

            userame_ = getDefaultInstance().getUserame();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 微信昵称
         * </pre>
         *
         * <code>bytes nickname = 11;</code>
         */
        @Override
        public com.google.protobuf.ByteString getNickname() {
            return nickname_;
        }

        /**
         * <pre>
         * 微信昵称
         * </pre>
         *
         * <code>bytes nickname = 11;</code>
         */
        public Builder setNickname(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            nickname_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 微信昵称
         * </pre>
         *
         * <code>bytes nickname = 11;</code>
         */
        public Builder clearNickname() {

            nickname_ = getDefaultInstance().getNickname();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 用户插件
         * </pre>
         *
         * <code>bytes userExt = 12;</code>
         */
        @Override
        public com.google.protobuf.ByteString getUserExt() {
            return userExt_;
        }

        /**
         * <pre>
         * 用户插件
         * </pre>
         *
         * <code>bytes userExt = 12;</code>
         */
        public Builder setUserExt(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            userExt_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 用户插件
         * </pre>
         *
         * <code>bytes userExt = 12;</code>
         */
        public Builder clearUserExt() {

            userExt_ = getDefaultInstance().getUserExt();
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:User)
    }

}

