// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wxipad.proto;

public interface WechatMsgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:WechatMsg)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    boolean hasBaseMsg();

    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    BaseMsg getBaseMsg();

    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    BaseMsgOrBuilder getBaseMsgOrBuilder();

    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    String getToken();

    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
    getTokenBytes();

    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    String getVersion();

    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    com.google.protobuf.ByteString
    getVersionBytes();

    /**
     * <pre>
     * 消息时间戳
     * </pre>
     *
     * <code>int32 timeStamp = 4;</code>
     */
    int getTimeStamp();

    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    String getIP();

    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    com.google.protobuf.ByteString
    getIPBytes();
}
