// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wxipad.proto;

/**
 * <pre>
 * 完整的grpc结构体
 * </pre>
 * <p>
 * Protobuf type {@code WechatMsg}
 */
public final class WechatMsg extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:WechatMsg)
        WechatMsgOrBuilder {
    public static final int BASEMSG_FIELD_NUMBER = 1;
    public static final int TOKEN_FIELD_NUMBER = 2;
    public static final int VERSION_FIELD_NUMBER = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    public static final int IP_FIELD_NUMBER = 5;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:WechatMsg)
    private static final WechatMsg DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<WechatMsg>
            PARSER = new com.google.protobuf.AbstractParser<WechatMsg>() {
        public WechatMsg parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new WechatMsg(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new WechatMsg();
    }

    private BaseMsg baseMsg_;
    private volatile Object token_;
    private volatile Object version_;
    private int timeStamp_;
    private volatile Object iP_;
    private byte memoizedIsInitialized = -1;

    // Use WechatMsg.newBuilder() to construct.
    private WechatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private WechatMsg() {
        token_ = "";
        version_ = "";
        timeStamp_ = 0;
        iP_ = "";
    }

    private WechatMsg(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        BaseMsg.Builder subBuilder = null;
                        if (baseMsg_ != null) {
                            subBuilder = baseMsg_.toBuilder();
                        }
                        baseMsg_ = input.readMessage(BaseMsg.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(baseMsg_);
                            baseMsg_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        token_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        version_ = s;
                        break;
                    }
                    case 32: {

                        timeStamp_ = input.readInt32();
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        iP_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return WechatProto.internal_static_WechatMsg_descriptor;
    }

    public static WechatMsg parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static WechatMsg parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static WechatMsg parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static WechatMsg parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static WechatMsg parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static WechatMsg parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static WechatMsg parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static WechatMsg parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static WechatMsg parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static WechatMsg parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static WechatMsg parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static WechatMsg parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(WechatMsg prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static WechatMsg getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<WechatMsg> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return WechatProto.internal_static_WechatMsg_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        WechatMsg.class, Builder.class);
    }

    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    @Override
    public boolean hasBaseMsg() {
        return baseMsg_ != null;
    }

    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    @Override
    public BaseMsg getBaseMsg() {
        return baseMsg_ == null ? BaseMsg.getDefaultInstance() : baseMsg_;
    }

    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    @Override
    public BaseMsgOrBuilder getBaseMsgOrBuilder() {
        return getBaseMsg();
    }

    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    @Override
    public String getToken() {
        Object ref = token_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            token_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            token_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    @Override
    public String getVersion() {
        Object ref = version_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            version_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            version_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 消息时间戳
     * </pre>
     *
     * <code>int32 timeStamp = 4;</code>
     */
    @Override
    public int getTimeStamp() {
        return timeStamp_;
    }

    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    @Override
    public String getIP() {
        Object ref = iP_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            iP_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getIPBytes() {
        Object ref = iP_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            iP_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (baseMsg_ != null) {
            output.writeMessage(1, getBaseMsg());
        }
        if (!getTokenBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
        }
        if (!getVersionBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
        }
        if (timeStamp_ != 0) {
            output.writeInt32(4, timeStamp_);
        }
        if (!getIPBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, iP_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (baseMsg_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getBaseMsg());
        }
        if (!getTokenBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
        }
        if (!getVersionBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
        }
        if (timeStamp_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, timeStamp_);
        }
        if (!getIPBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, iP_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof WechatMsg)) {
            return super.equals(obj);
        }
        WechatMsg other = (WechatMsg) obj;

        boolean result = true;
        result = result && (hasBaseMsg() == other.hasBaseMsg());
        if (hasBaseMsg()) {
            result = result && getBaseMsg()
                    .equals(other.getBaseMsg());
        }
        result = result && getToken()
                .equals(other.getToken());
        result = result && getVersion()
                .equals(other.getVersion());
        result = result && (getTimeStamp()
                == other.getTimeStamp());
        result = result && getIP()
                .equals(other.getIP());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasBaseMsg()) {
            hash = (37 * hash) + BASEMSG_FIELD_NUMBER;
            hash = (53 * hash) + getBaseMsg().hashCode();
        }
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimeStamp();
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIP().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<WechatMsg> getParserForType() {
        return PARSER;
    }

    @Override
    public WechatMsg getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * 完整的grpc结构体
     * </pre>
     * <p>
     * Protobuf type {@code WechatMsg}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:WechatMsg)
            WechatMsgOrBuilder {
        private BaseMsg baseMsg_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                BaseMsg, BaseMsg.Builder, BaseMsgOrBuilder> baseMsgBuilder_;
        private Object token_ = "";
        private Object version_ = "";
        private int timeStamp_;
        private Object iP_ = "";

        // Construct using WechatMsg.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return WechatProto.internal_static_WechatMsg_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return WechatProto.internal_static_WechatMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            WechatMsg.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            if (baseMsgBuilder_ == null) {
                baseMsg_ = null;
            } else {
                baseMsg_ = null;
                baseMsgBuilder_ = null;
            }
            token_ = "";

            version_ = "";

            timeStamp_ = 0;

            iP_ = "";

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return WechatProto.internal_static_WechatMsg_descriptor;
        }

        @Override
        public WechatMsg getDefaultInstanceForType() {
            return WechatMsg.getDefaultInstance();
        }

        @Override
        public WechatMsg build() {
            WechatMsg result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public WechatMsg buildPartial() {
            WechatMsg result = new WechatMsg(this);
            if (baseMsgBuilder_ == null) {
                result.baseMsg_ = baseMsg_;
            } else {
                result.baseMsg_ = baseMsgBuilder_.build();
            }
            result.token_ = token_;
            result.version_ = version_;
            result.timeStamp_ = timeStamp_;
            result.iP_ = iP_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return (Builder) super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof WechatMsg) {
                return mergeFrom((WechatMsg) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(WechatMsg other) {
            if (other == WechatMsg.getDefaultInstance()) {
                return this;
            }
            if (other.hasBaseMsg()) {
                mergeBaseMsg(other.getBaseMsg());
            }
            if (!other.getToken().isEmpty()) {
                token_ = other.token_;
                onChanged();
            }
            if (!other.getVersion().isEmpty()) {
                version_ = other.version_;
                onChanged();
            }
            if (other.getTimeStamp() != 0) {
                setTimeStamp(other.getTimeStamp());
            }
            if (!other.getIP().isEmpty()) {
                iP_ = other.iP_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            WechatMsg parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (WechatMsg) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        @Override
        public boolean hasBaseMsg() {
            return baseMsgBuilder_ != null || baseMsg_ != null;
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        @Override
        public BaseMsg getBaseMsg() {
            if (baseMsgBuilder_ == null) {
                return baseMsg_ == null ? BaseMsg.getDefaultInstance() : baseMsg_;
            } else {
                return baseMsgBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        public Builder setBaseMsg(BaseMsg value) {
            if (baseMsgBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                baseMsg_ = value;
                onChanged();
            } else {
                baseMsgBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        public Builder setBaseMsg(
                BaseMsg.Builder builderForValue) {
            if (baseMsgBuilder_ == null) {
                baseMsg_ = builderForValue.build();
                onChanged();
            } else {
                baseMsgBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        public Builder mergeBaseMsg(BaseMsg value) {
            if (baseMsgBuilder_ == null) {
                if (baseMsg_ != null) {
                    baseMsg_ =
                            BaseMsg.newBuilder(baseMsg_).mergeFrom(value).buildPartial();
                } else {
                    baseMsg_ = value;
                }
                onChanged();
            } else {
                baseMsgBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        public Builder clearBaseMsg() {
            if (baseMsgBuilder_ == null) {
                baseMsg_ = null;
                onChanged();
            } else {
                baseMsg_ = null;
                baseMsgBuilder_ = null;
            }

            return this;
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        public BaseMsg.Builder getBaseMsgBuilder() {

            onChanged();
            return getBaseMsgFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        @Override
        public BaseMsgOrBuilder getBaseMsgOrBuilder() {
            if (baseMsgBuilder_ != null) {
                return baseMsgBuilder_.getMessageOrBuilder();
            } else {
                return baseMsg_ == null ?
                        BaseMsg.getDefaultInstance() : baseMsg_;
            }
        }

        /**
         * <pre>
         * 请求消息结构体
         * </pre>
         *
         * <code>.BaseMsg baseMsg = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                BaseMsg, BaseMsg.Builder, BaseMsgOrBuilder>
        getBaseMsgFieldBuilder() {
            if (baseMsgBuilder_ == null) {
                baseMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        BaseMsg, BaseMsg.Builder, BaseMsgOrBuilder>(
                        getBaseMsg(),
                        getParentForChildren(),
                        isClean());
                baseMsg_ = null;
            }
            return baseMsgBuilder_;
        }

        /**
         * <pre>
         * 授权TOKEN,CODE,V3_
         * </pre>
         *
         * <code>string token = 2;</code>
         */
        @Override
        public String getToken() {
            Object ref = token_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                token_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 授权TOKEN,CODE,V3_
         * </pre>
         *
         * <code>string token = 2;</code>
         */
        public Builder setToken(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            token_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 授权TOKEN,CODE,V3_
         * </pre>
         *
         * <code>string token = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getTokenBytes() {
            Object ref = token_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                token_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 授权TOKEN,CODE,V3_
         * </pre>
         *
         * <code>string token = 2;</code>
         */
        public Builder setTokenBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            token_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 授权TOKEN,CODE,V3_
         * </pre>
         *
         * <code>string token = 2;</code>
         */
        public Builder clearToken() {

            token_ = getDefaultInstance().getToken();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 协议版本
         * </pre>
         *
         * <code>string version = 3;</code>
         */
        @Override
        public String getVersion() {
            Object ref = version_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                version_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 协议版本
         * </pre>
         *
         * <code>string version = 3;</code>
         */
        public Builder setVersion(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            version_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 协议版本
         * </pre>
         *
         * <code>string version = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getVersionBytes() {
            Object ref = version_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                version_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 协议版本
         * </pre>
         *
         * <code>string version = 3;</code>
         */
        public Builder setVersionBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            version_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 协议版本
         * </pre>
         *
         * <code>string version = 3;</code>
         */
        public Builder clearVersion() {

            version_ = getDefaultInstance().getVersion();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 消息时间戳
         * </pre>
         *
         * <code>int32 timeStamp = 4;</code>
         */
        @Override
        public int getTimeStamp() {
            return timeStamp_;
        }

        /**
         * <pre>
         * 消息时间戳
         * </pre>
         *
         * <code>int32 timeStamp = 4;</code>
         */
        public Builder setTimeStamp(int value) {

            timeStamp_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 消息时间戳
         * </pre>
         *
         * <code>int32 timeStamp = 4;</code>
         */
        public Builder clearTimeStamp() {

            timeStamp_ = 0;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 外网 IP
         * </pre>
         *
         * <code>string iP = 5;</code>
         */
        @Override
        public String getIP() {
            Object ref = iP_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                iP_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 外网 IP
         * </pre>
         *
         * <code>string iP = 5;</code>
         */
        public Builder setIP(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            iP_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 外网 IP
         * </pre>
         *
         * <code>string iP = 5;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getIPBytes() {
            Object ref = iP_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                iP_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 外网 IP
         * </pre>
         *
         * <code>string iP = 5;</code>
         */
        public Builder setIPBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            iP_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 外网 IP
         * </pre>
         *
         * <code>string iP = 5;</code>
         */
        public Builder clearIP() {

            iP_ = getDefaultInstance().getIP();
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:WechatMsg)
    }

}

