// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wxipad.proto;

public final class WechatProto {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_WechatMsg_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_WechatMsg_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_BaseMsg_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_BaseMsg_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_User_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_User_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\021WechatProto.proto\"e\n\tWechatMsg\022\031\n\007base" +
                        "Msg\030\001 \001(\0132\010.BaseMsg\022\r\n\005token\030\002 \001(\t\022\017\n\007ve" +
                        "rsion\030\003 \001(\t\022\021\n\ttimeStamp\030\004 \001(\005\022\n\n\002iP\030\005 \001" +
                        "(\t\"\251\001\n\007BaseMsg\022\013\n\003ret\030\001 \001(\005\022\013\n\003cmd\030\002 \001(\005" +
                        "\022\016\n\006cmdUrl\030\003 \001(\t\022\021\n\tshortHost\030\004 \001(\t\022\020\n\010l" +
                        "ongHost\030\005 \001(\t\022\023\n\004user\030\006 \001(\0132\005.User\022\020\n\010lo" +
                        "ngHead\030\007 \001(\014\022\020\n\010payloads\030\010 \001(\014\022\026\n\016playlo" +
                        "adextend\030\t \001(\014\"\347\001\n\004User\022\013\n\003uin\030\001 \001(\003\022\017\n\007" +
                        "cookies\030\002 \001(\014\022\022\n\nsessionKey\030\003 \001(\014\022\020\n\010dev" +
                        "iceId\030\004 \001(\t\022\022\n\ndeviceType\030\005 \001(\t\022\022\n\ndevic" +
                        "eName\030\006 \001(\t\022\026\n\016currentsyncKey\030\007 \001(\014\022\022\n\nm" +
                        "axSyncKey\030\010 \001(\014\022\023\n\013autoAuthKey\030\t \001(\014\022\017\n\007" +
                        "userame\030\n \001(\t\022\020\n\010nickname\030\013 \001(\014\022\017\n\007userE" +
                        "xt\030\014 \001(\01421\n\006Wechat\022\'\n\013helloWechat\022\n.Wech" +
                        "atMsg\032\n.WechatMsg\"\000B \n\017wechat.protobufB\013" +
                        "WechatProtoP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    @Override
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_WechatMsg_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_WechatMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_WechatMsg_descriptor,
                new String[]{"BaseMsg", "Token", "Version", "TimeStamp", "IP",});
        internal_static_BaseMsg_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_BaseMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_BaseMsg_descriptor,
                new String[]{"Ret", "Cmd", "CmdUrl", "ShortHost", "LongHost", "User", "LongHead", "Payloads", "Playloadextend",});
        internal_static_User_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_User_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_User_descriptor,
                new String[]{"Uin", "Cookies", "SessionKey", "DeviceId", "DeviceType", "DeviceName", "CurrentsyncKey", "MaxSyncKey", "AutoAuthKey", "Userame", "Nickname", "UserExt",});
    }

    private WechatProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
